# 异常处理
## 1. 基本使用

> - throw int类型数据，那catch(int)；throw double类型数据，那catch(double)；
> - 但类型众多，不可能都写上，就可以用catch(...)表示；

```C++
int MySub(int a, int b)
{
	if (b == 0)
		// throw - 1;
		// throw 3.111;
		throw "sdfwr45";
	return a / b;
}

void test()
{
	int a = 10;
	int b = 0;
	try
	{
		cout << MySub(a, b) << endl;
	}
	catch(int)
	{
		cout << "int 类型异常" << endl;
	}
	catch(double)
	{
		cout << "double 类型异常" << endl;
	}
	catch(...)
	{
		cout << "其它 类型异常" << endl;
	}
}
int main() 
{
	test();
	return 0;
}
```

## 2. 自定义异常类
> 1. throw 后面跟自定义的类名：throw MyException();
> 2. catch中写自定义类的实例化对象：catch(MyException e) 

```C++
// 自定义异常类
class MyException
{
public:
	void PrintError()
	{
		cout << "自定义异常输出" << endl;
	}
};

int MySub(int a, int b)
{
	if (b == 0)
		throw MyException();    // throw 后面跟自定义的类名
	return a / b;
}

void test()
{
	int a = 10;
	int b = 0;
	try
	{
		cout << MySub(a, b) << endl;
	}
	catch(MyException & e)    // catch中写自定义类的实例化对象
	{
		e.PrintError();
	}

}
int main() 
{
	test();
	return 0;
}
```

## 3. 系统标准异常使用
> + 开头要加上：#include <stdexcept>
> + 异常类型种类很多，out_of_range就是其中一种；
> + catch(out_of_range & e)，常用 & ；
> + e.what() 可以看出自己写的异常内容；
```C++
#include <stdexcept>

class Person
{
public:
	Person(string name, int age)
	{
		this->m_name = name;
		if (age < 0 || age > 200)
		{
			throw out_of_range("年龄越界");
		}
		this->m_age = age;
	}
	string m_name;
	int m_age;
};

void test()
{
	try
	{
		Person p("Tom", 2010);
	}
	catch(out_of_range & e)
	{
		cout << e.what() << endl;   // 年龄越界
	}
}
int main() 
{
	test();
	return 0;
}
```